#!/bin/bash

#source ~/ws_baxter/devel/setup.bash

rosrun baxter_examples xdisplay_image.py --file=RMIT.png

( rosrun baxter_tools tuck_arms.py -u ;
  rosrun baxter_tools tuck_arms.py -t
) &

rosrun mobility_base_examples motion_demo.py &
