#!/bin/bash

cp vxlab.world /usr/share/gazebo-7/worlds/empty.world

cd ~/ws_baxter
#HOSTNAME=`hostname`
HOSTNAME=127.0.0.1
#export ROS_IP=${HOSTNAME}.vx.rmit.edu.au
export ROS_IP=${HOSTNAME}
#export ROS_MASTER_URI=http://${HOSTNAME}.vx.rmit.edu.au:11311
export ROS_MASTER_URI=http://${HOSTNAME}:11311

export export MB_LASER_BIRDCAGE_R2000=1
export MB_LASER_BIRDCAGE_R2000_FREQ=50
export MB_LASER_BIRDCAGE_R2000_SAMPLES=3600

source devel/setup.bash
roslaunch mobility_base_gazebo mobility_base_empty_world.launch baxter:=true
#roslaunch baxter_gazebo baxter_world.launch
